#!/usr/bin/env bash

BACKUP="/home/${USER}/.config/xkb_caps_backup"
TMPFILE="/tmp/xkbmap"

start_fix() {
  mkdir -p "/home/${USER}/.config"
  xkbcomp -xkb "${DISPLAY:-:0}" "${TMPFILE}"
  if [[ ! -f "${BACKUP}" ]]; then
    perl -0777 -ne 'print $& if /key <CAPS> {.*?};/s' "${TMPFILE}" > "${BACKUP}" && \
    echo "Caps Lock config backed up to ${BACKUP}..."
  fi
  perl -0777 -i -pe 's/key <CAPS> {.*?};/key <CAPS> {\n\trepeat=no,\n\ttype[group1]="ALPHABETIC",\n\tsymbols[group1]=[ Caps_Lock, Caps_Lock],\n\tactions[group1]=[ LockMods(modifiers=Lock), Private(type=3,data[0]=1,data[1]=3,data[2]=3)]\n};/s' "${TMPFILE}"
  xkbcomp -w 0 "${TMPFILE}" "${DISPLAY:-:0}"
  echo "Caps Lock config switched to Mac/Windows style."
}

stop_fix() {
  mkdir -p "/home/${USER}/.config"
  if [[ ! -f "${BACKUP}" ]]; then
    echo "No backup found. Using default config..."
    echo -e -n 'key <CAPS> {\n\ttype= "ONE_LEVEL",\n\tsymbols[Group1]= [      Caps_Lock ]\n    };' > "${BACKUP}"
  fi
  xkbcomp -xkb "${DISPLAY:-:0}" "${TMPFILE}"
  perl -0777 -i -pe "s/key <CAPS> {[^}]*};/`cat ${BACKUP}`/s" "${TMPFILE}"
  xkbcomp -w 0 "${TMPFILE}" "${DISPLAY:-:0}"
  rm -f "${BACKUP}"
  echo "Caps Lock config reverted to Linux style."
}

enable_fix() {
  mkdir -p "/home/${USER}/.config/autostart"
  echo -e "[Desktop Entry]\nType=Application\nExec=/usr/bin/capsfix start\nHidden=false\nX-GNOME-Autostart-enabled=true\nName=Caps Lock State Fix\nComment=Fixes Caps Lock to work like it does on Mac and Windows" > "/home/${USER}/.config/autostart/capsfix.desktop"
  start_fix
  echo "Config will remain Mac/Windows style until disabled."
}

disable_fix() {
  rm -rf "/home/${USER}/.config/autostart/capsfix.desktop"
  stop_fix
  echo "Config will remain Linux style until enabled again."
}

case "${1}" in
  enable|disable|start|stop) "${1}"_fix ;;
  *)
    echo "Usage: ${0##*/} {enable|disable|start|stop}"
    exit 1
    ;;
esac
